### Ping
GET http://localhost:3000/ping


### Get all projects
GET http://localhost:3000/projects

### Get project by id
GET http://localhost:3000/projects/1

### Create project
POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "Project 2",
    "description": "Description 2"
}

### Update project
PATCH http://localhost:3000/projects/1
Content-Type: application/json

{
    "description": "Description 2"
}

### Delete project
DELETE http://localhost:3000/projects/1



### Get all posts
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/1

### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello234",
    "content": "World234",
    "projectId": "rd3ags9pknrrbqvo9bz587qj"
}

### Update post
PATCH http://localhost:3000/posts/b4ds2ht0t3m0yd7jbq1azb9q
Content-Type: application/json

{
    "content": "World123"
}

### Delete post
DELETE http://localhost:3000/posts/awyt15p9hz24r8pk5l9di1xd



### signup
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "qwe123!@#"
}

### signin
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "qwe123!@#"
}

### signout
POST http://localhost:3000/signout
Content-Type: application/json
