### Ping
GET http://localhost:3000/ping

### Get all posts
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/1

### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "content": "World"
}

### Update post
PATCH http://localhost:3000/posts/b4ds2ht0t3m0yd7jbq1azb9q
Content-Type: application/json

{
    "content": "World123"
}

### Delete post
DELETE http://localhost:3000/posts/awyt15p9hz24r8pk5l9di1xd